title: Andrej Istomin
email: your-email@example.com
description: >-
  Software engineer, hobby musician, wandering philosopher.

baseurl: ''
url: 'https://aistomin.com'

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-sitemap

# Exclude from Jekyll build
exclude:
  - playwright
  - Gemfile
  - Gemfile.lock
  - README.md
  - Dockerfile
  - docker-compose.yml
  - "*.sh"

future: true
