services:
  jekyll:
    image: jekyll/jekyll:latest
    ports:
      - '4000:4000'
      - '35729:35729'
    volumes:
      - .:/srv/jekyll
    working_dir: /srv/jekyll
    command: sh -c "rm -rf _site .jekyll-cache && bundle install && bundle exec jekyll serve --host 0.0.0.0 --livereload --force_polling --watch"
    environment:
      - JEKYLL_ENV=development
      - POLLING=true
